
services:
  frontend:
    build: ./FrontEnd/eventos
    container_name: frontend
    ports:
      - '8080:8080'
  backend-obtiene-productos:
    build: ./Servicios/ObtieneProductos/
    container_name: obtieneProductos
    ports:
      - '3001:3001'
    stdin_open: true
    tty: true
  backend-inserta-suarios:
    build: ./Servicios/InsertaUsuarios/
    container_name: insertaUsuarios
    ports:
      - '3004:3004'
    stdin_open: true
    tty: true