
services:
  frontend:
    build: ./FrontEnd/eventos
    container_name: frontend
    ports:
      - '8080:8080'
    depends_on:
      - backend-obtiene-productos
      - backend-inserta-suarios
    networks:
      - net-app
  backend-obtiene-productos:
    build: ./Servicios/ObtieneProductos/
    container_name: obtieneProductos
    ports:
      - '3001:3001'
    environment:
      - PORT=${PORT_LISTPRODUCTOS}
      - SQLPORT
      - SQLUSERNAME
      - SQLHOST
      - SQLPASS
      - SQLDATABASE
    stdin_open: true
    tty: true
    networks:
      - net-app
  backend-inserta-suarios:
    build: ./Servicios/InsertaUsuarios/
    container_name: insertaUsuarios
    ports:
      - '3004:3004'
    environment:
      - PORT=${PORT_USUARIOS}
      - SQLPORT
      - SQLUSERNAME
      - SQLHOST
      - SQLPASS
      - SQLDATABASE
    stdin_open: true
    tty: true
    networks:
      - net-app
networks:
  net-app:
    driver: bridge
